stages:
  data_ingestion:
    cmd: python3 src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.train_size_fraud
    - data_ingestion.train_size_authentic
    - data_ingestion.val_size_fraud
    - data_ingestion.val_size_authentic
    - data_ingestion.test_size_fraud
    - data_ingestion.test_size_authentic
    - data_ingestion.predict_size_fraud
    - data_ingestion.predict_size_authentic
    outs:
    - data/raw

  data_preprocessing:
    cmd: python3 src/data/data_preprocessing.py
    deps:
    - src/data/data_preprocessing.py
    - data/raw/train.csv
    - data/raw/val.csv
    - data/raw/test.csv
    - data/raw/predict.csv
    params:
      - data_preprocessing.scaler_method
    outs:
    - data/processed
    - artifacts/scaler.pkl

  