data_ingestion:
  train_size_fraud: 0.15
  train_size_authentic: 0.55
  val_size_fraud: 0.3
  val_size_authentic: 0.15
  test_size_fraud: 0.50
  test_size_authentic: 0.25
  predict_size_fraud: 0.05 
  predict_size_authentic: 0.05
   
data_preprocessing:
  scaler_method: 'standardscaler'
  imputer_method: 'knnimputer'   

model_building:
  models:
    logistic_regression:
      class: "sklearn.linear_model.LogisticRegression"
      params:
        C: 1.0
        max_iter: 1000
        random_state: 42
        n_jobs: -1
    random_forest:
      class: "sklearn.ensemble.RandomForestClassifier"
      params:
        n_estimators: 200
        max_depth: 10
        random_state: 42
        n_jobs: -1
    gradient_boosting:
      class: "sklearn.ensemble.HistGradientBoostingClassifier"
      params:
        max_iter: 200
        learning_rate: 0.1
        max_depth: 10
        random_state: 42
    lgbm:
      class: "lightgbm.LGBMClassifier"
      params:
        n_estimators: 300
        learning_rate: 0.05
        random_state: 42
        n_jobs: -1
    xgboost:
      class: "xgboost.XGBClassifier"
      params:
        n_estimators: 300
        learning_rate: 0.05
        random_state: 42
        n_jobs: -1



model_evaluation:
  tracking_uri: "https://dagshub.com/takenking9879/MLOPS-project-Credit-Card-Fraud-Detection.mlflow"
  experiment_name: "credit-card-fraud"
  selection:
    # mode: "overall" | "specific" | "combined"
    # overall: usar métricas globales (accuracy, f1_score, recall, precision, roc_auc, ...)
    # specific: usar métricas por clase (ej. "1_recall", "0_precision", ...)
    # combined: mezcla overall y specific por combined_overall_weight
    mode: "combined"
    num_classes: 2                # opcional, ayuda a validar claves (0..num_classes-1)
    combined_overall_weight: 0.4  # solo si mode=="combined" (0..1)

    overall:
      accuracy: 0.0
      recall: 0.0
      precision: 0.0
      f1_score: 0.0
      roc_auc: 1.0

    specific:
      # Ejemplo: priorizar recall y precision de la clase 1
      "1_recall": 3
      "1_precision": 2
      # dejar en 0 o no definir para los demás
      "0_recall": 0
      "0_precision": 0
