data_ingestion:
  train_size_fraud: 0.15
  train_size_authentic: 0.55
  val_size_fraud: 0.3
  val_size_authentic: 0.15
  test_size_fraud: 0.50
  test_size_authentic: 0.25
  predict_size_fraud: 0.05 
  predict_size_authentic: 0.05
   
data_preprocessing:
  scaler_method: 'standardscaler'   
  
model_building:
  ngram_range: [1, 3]  
  max_features: 1000
  learning_rate: 0.09
  max_depth: 20
  n_estimators: 367